# Generated by Django 6.1 on 2026-09-08 15:25

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SpeechPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='speech part')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entities_per_page', models.IntegerField(default=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='group')),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=core.models.get_exercise_name, max_length=100, verbose_name='title')),
                ('created', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='from date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='to date')),
                ('failed', models.IntegerField(blank=True, null=True, verbose_name='wrong more than')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercisetype', verbose_name='exercise type')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='group')),
                ('speech_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.speechpart', verbose_name='speech part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=255, verbose_name='sentence')),
                ('translation', models.CharField(blank=True, max_length=300, null=True, verbose_name='translation')),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['body'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=40, verbose_name='signature')),
                ('translation', models.TextField(max_length=300, verbose_name='translation')),
                ('transcription', models.CharField(blank=True, max_length=40, null=True, verbose_name='transcription')),
                ('created', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, verbose_name='use in tests')),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, to='core.group', verbose_name='groups')),
                ('sentences', models.ManyToManyField(blank=True, to='core.sentence', verbose_name='sentences')),
                ('speech_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.speechpart', verbose_name='speech part')),
                ('synonyms', models.ManyToManyField(blank=True, to='core.word', verbose_name='synonyms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signature'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_passed', models.BooleanField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.word')),
            ],
        ),
    ]
